name: Auto Release On New Tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Auto Release On New Tag
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build
        run: pyinstaller main.spec
      - name: Compress
        run: |
          cd dist
          7z a ../GenshinAutoFish.zip
          7z a ../GenshinAutoFish.7z -mx9
          tar -cvzf ../GenshinAutoFish.tar.gz *
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.XGITHUB_TOKEN}}
          prerelease: false
          files: |
            GenshinAutoFish.zip
            GenshinAutoFish.7z
            GenshinAutoFish.tar.gz
